<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UniversitiesTableSeeder extends Seeder
{
    public function run()
    {
        $universities = [
            [
                'uni_name' => 'University of Dhaka',
                'uni_type' => 'Public',
                'established_year' => 1921,
                'portal_code' => 'DU',
                'accreditation_status' => 'Accredited',
                'district' => 'Dhaka',
                'area' => 'Ramna',
                'website_url' => 'http://www.du.ac.bd',
                'email_address' => 'info@du.ac.bd',
                'phone_number' => '+880 2 9661900',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'Bangladesh University of Engineering and Technology',
                'uni_type' => 'Public',
                'established_year' => 1962,
                'portal_code' => 'BUET',
                'accreditation_status' => 'Accredited',
                'district' => 'Dhaka',
                'area' => 'Palashi',
                'website_url' => 'http://www.buet.ac.bd',
                'email_address' => 'info@buet.ac.bd',
                'phone_number' => '+880 2 55167100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'North South University',
                'uni_type' => 'Private',
                'established_year' => 1992,
                'portal_code' => 'NSU',
                'accreditation_status' => 'Accredited',
                'district' => 'Dhaka',
                'area' => 'Bashundhara',
                'website_url' => 'http://www.northsouth.edu',
                'email_address' => 'info@northsouth.edu',
                'phone_number' => '+880 2 55668200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'BRAC University',
                'uni_type' => 'Private',
                'established_year' => 2001,
                'portal_code' => 'BRACU',
                'accreditation_status' => 'Accredited',
                'district' => 'Dhaka',
                'area' => 'Mohakhali',
                'website_url' => 'http://www.bracu.ac.bd',
                'email_address' => 'info@bracu.ac.bd',
                'phone_number' => '+880 2 222264051',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'Jahangirnagar University',
                'uni_type' => 'Public',
                'established_year' => 1970,
                'portal_code' => 'JU',
                'accreditation_status' => 'Accredited',
                'district' => 'Dhaka',
                'area' => 'Savar',
                'website_url' => 'http://www.juniv.edu',
                'email_address' => 'info@juniv.edu',
                'phone_number' => '+880 2 7791045',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'East West University',
                'uni_type' => 'Private',
                'established_year' => 1996,
                'portal_code' => 'EWU',
                'accreditation_status' => 'Accredited',
                'district' => 'Dhaka',
                'area' => 'Aftabnagar',
                'website_url' => 'http://www.ewubd.edu',
                'email_address' => 'info@ewubd.edu',
                'phone_number' => '+880 2 9858261',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'American International University-Bangladesh',
                'uni_type' => 'Private',
                'established_year' => 1994,
                'portal_code' => 'AIUB',
                'accreditation_status' => 'Accredited',
                'district' => 'Dhaka',
                'area' => 'Kuratoli',
                'website_url' => 'http://www.aiub.edu',
                'email_address' => 'info@aiub.edu',
                'phone_number' => '+880 2 9894229',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'Independent University, Bangladesh',
                'uni_type' => 'Private',
                'established_year' => 1993,
                'portal_code' => 'IUB',
                'accreditation_status' => 'Accredited',
                'district' => 'Dhaka',
                'area' => 'Bashundhara',
                'website_url' => 'http://www.iub.edu.bd',
                'email_address' => 'info@iub.edu.bd',
                'phone_number' => '+880 2 8431645',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'University of Chittagong',
                'uni_type' => 'Public',
                'established_year' => 1966,
                'portal_code' => 'CU',
                'accreditation_status' => 'Accredited',
                'district' => 'Chittagong',
                'area' => 'Hathazari',
                'website_url' => 'http://www.cu.ac.bd',
                'email_address' => 'info@cu.ac.bd',
                'phone_number' => '+880 31 726311',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uni_name' => 'Khulna University of Engineering & Technology',
                'uni_type' => 'Public',
                'established_year' => 2003,
                'portal_code' => 'KUET',
                'accreditation_status' => 'Accredited',
                'district' => 'Khulna',
                'area' => 'Fulbarigate',
                'website_url' => 'http://www.kuet.ac.bd',
                'email_address' => 'info@kuet.ac.bd',
                'phone_number' => '+880 41 769468',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('universities')->insert($universities);
    }
}